# Generated by Django 5.2.5 on 2025-08-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videopost',
            name='platforms',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('dailymotion', 'Dailymotion')], max_length=50),
        ),
    ]
